### ISSUE TITLE
drd/tests/fork-parallel is failing [FreeBSD 13.0 amd64]

### ISSUE THREAD

**Issue by paulfloyd** [paulfloyd/freebsd_valgrind#170]
On my upgraded desktop, this extra error

Thread 3:
Conflicting store by thread 3 at 0x........ size 1
   at 0x........: ??? (in /...libc...)
   by 0x........: ??? (in /...libc...)
   by 0x........: _malloc_postfork (in /...libc...)
   by 0x........: start_thread
   by 0x........: start_thread
   by 0x........: startproc (fork.c:?)
   by 0x........: vgDrd_thread_wrapper (drd_pthread_intercepts.c:?)
   by 0x........: start_thread
Allocation context: unknown.

The error is intermittent. Likely to need a suppression.

**Comment by paulfloyd** [comment]
There is also a problem with debuginfo. gdb gives

(gdb) bt  
#0  __je_malloc_mutex_postfork_parent (tsdn=0x58cb090, mutex=0x50ab8d8)
    at jemalloc_mutex.c:212
#1  0x0000000004a20f35 in __je_arena_postfork_parent (tsdn=0x58cb090, 
    arena=0x50a6980) at jemalloc_arena.c:2245
#2  0x0000000004a18e4a in _malloc_postfork () at jemalloc_jemalloc.c:3963
#3  0x0000000004879510 in thr_fork_impl (a=a@entry=0x7dadfdee8)
    at /usr/src/lib/libthr/thread/thr_fork.c:283
#4  0x0000000004879368 in __thr_fork ()
    at /usr/src/lib/libthr/thread/thr_fork.c:314
#5  0x0000000000201c65 in startproc (arg=0x204004 <pids+4>) at fork.c:18
#6  0x000000000485f019 in vgDrd_thread_wrapper (arg=<optimized out>)
    at drd_pthread_intercepts.c:491
#7  0x000000000487882b in thread_start (curthread=0x4ca6a50)
    at /usr/src/lib/libthr/thread/thr_create.c:292
#8  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7dadfe000

The failure is hopefully fixed with

commit 5f8211aa603c173f5ca6049e9fde2bf460fb3758
